#!/usr/bin/env python3
"""Generate ``docker/compose.yaml`` from the catalogue.

Each :class:`BackendInfo` in the catalogue with a non-None ``deploy``
field becomes a compose service block. The output also includes the
hand-written gateway block and the ``include: compose.cpu.yaml`` line
so the existing Phase-1 quickstart keeps working.

Run after editing any adapter's ``deploy``:

    python scripts/gen_compose.py
    git diff docker/compose.yaml   # confirm intentional drift only

A pytest invariant (tests/backends/test_compose_drift.py) ensures CI
catches drift between catalogue and committed compose.yaml.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from chemclaw_retro.backends.adapters._catalogue import CATALOGUE  # noqa: E402
from chemclaw_retro.schemas import BackendInfo  # noqa: E402

HEADER = """\
# AUTO-GENERATED by scripts/gen_compose.py from the backend catalogue.
# Do NOT edit by hand — change the ``deploy`` field on the matching
# adapter in src/chemclaw_retro/backends/adapters/ and re-run the
# generator.
#
# Use `--profile <name>` to bring up subsets:
#   docker compose --profile template     up
#   docker compose --profile transformer  up
#   docker compose --profile graph        up
#   docker compose --profile planner      up
#   docker compose --profile llm          up
#   docker compose --profile biocatalysis up
#
# Without a profile, only the gateway + Phase-1 backends start (see
# compose.cpu.yaml).

include:
  - compose.cpu.yaml

x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
  volumes:
    - ../weights:/weights:ro
  restart: unless-stopped

x-cpu: &cpu
  volumes:
    - ../weights:/weights:ro
  restart: unless-stopped

services:
"""


_FAMILY_HEADER = {
    "template": "  # ---- Template family ----",
    "transformer": "  # ---- Transformer family ----",
    "graph": "  # ---- Graph family ----",
    "planner": "  # ---- Heavy planners ----",
    "hybrid": "  # ---- Hybrid (planner-side) ----",
    "llm": "  # ---- LLM-style (single shared image, env-driven) ----",
    "biocatalysis": "  # ---- Biocatalysis / natural products ----",
    "similarity": "  # ---- Similarity (CPU) ----",
}


def _render_block(info: BackendInfo) -> str:
    d = info.deploy
    assert d is not None
    anchor = "*gpu" if d.gpu else "*cpu"
    profiles = "[" + ", ".join(d.profiles) + "]"
    lines = [
        f"  {d.service}:",
        f"    <<: {anchor}",
        f"    profiles: {profiles}",
        f"    build: {{ context: .., dockerfile: {d.dockerfile} }}",
        f'    ports: ["{d.host_port}:9000"]',
    ]
    if d.environment:
        lines.append("    environment:")
        for k, v in d.environment.items():
            lines.append(f"      {k}: {_yaml_value(v)}")
    return "\n".join(lines) + "\n"


def _yaml_value(v: str) -> str:
    """Quote env values whose raw form would parse as a non-string in
    YAML (commas, colons, leading $, leading digit). Compose-style
    ``${VAR:-default}`` is preserved verbatim — bash interpolation
    happens before YAML parsing in modern compose, but quote for safety.
    """
    if v == "":
        return '""'
    if any(c in v for c in ":,") or v.startswith("$") or v[0].isdigit():
        return '"' + v.replace('"', '\\"') + '"'
    return v


def render() -> str:
    by_family: dict[str, list[BackendInfo]] = {}
    for info in CATALOGUE.values():
        if info.deploy is None:
            continue
        by_family.setdefault(info.family, []).append(info)

    out = [HEADER]
    for family in sorted(by_family.keys()):
        out.append(_FAMILY_HEADER.get(family, f"  # ---- {family} ----"))
        out.append("")
        for info in sorted(by_family[family], key=lambda i: i.name):
            out.append(_render_block(info))
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if docker/compose.yaml is stale"
    )
    parser.add_argument("--out", type=Path, default=ROOT / "docker" / "compose.yaml")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != rendered:
            sys.stderr.write(
                f"{args.out} is stale relative to the catalogue; "
                "run `python scripts/gen_compose.py` and commit the diff.\n"
            )
            sys.exit(1)
        return

    args.out.write_text(rendered)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
